<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            'Not yet Defined',
            'Afghan',
            'Albanian',
            'Algerian',
            'Argentinian',
            'Australian',
            'Austrian',
            'Bangladeshi',
            'Belgian',
            'Bolivian',
            'Batswana',
            'Brazilian',
            'Bulgarian',
            'Cambodian',
            'Cameroonian',
            'Canadian',
            'Chilean',
            'Chinese',
            'Colombian',
            'Costa Rican',
            'Croatian',
            'Cuban',
            'Czech',
            'Danish',
            'Dominican',
            'Ecuadorian',
            'Egyptian',
            'Salvadorian',
            'English',
            'Estonian',
            'Ethiopian',
            'Fijian',
            'Filipino',
            'Finnish',
            'French',
            'German',
            'Ghanaian',
            'Greek',
            'Guatemalan',
            'Haitian',
            'Honduran',
            'Hungarian',
            'Icelandic',
            'Indian',
            'Indonesian',
            'Iranian',
            'Iraqi',
            'Irish',
            'Israeli',
            'Italian',
            'Jamaican',
            'Japanese',
            'Jordanian',
            'Kenyan',
            'Kuwaiti',
            'Lao',
            'Latvian',
            'Lebanese',
            'Libyan',
            'Lithuanian',
            'Malaysian',
            'Malian',
            'Maltese',
            'Mexican',
            'Mongolian',
            'Moroccan',
            'Mozambican',
            'Namibian',
            'Nepalese',
            'Dutch',
            'New Zealand',
            'Nicaraguan',
            'Nigerian',
            'Norwegian',
            'Pakistani',
            'Panamanian',
            'Paraguayan',
            'Peruvian',
            'Polish',
            'Portuguese',
            'Romanian',
            'Russian',
            'Saudi',
            'Scottish',
            'Senegalese',
            'Serbian',
            'Singaporean',
            'Slovak',
            'South African',
            'Korean',
            'Spanish',
            'Sri Lankan',
            'Sudanese',
            'Swedish',
            'Swiss',
            'Syrian',
            'Taiwanese',
            'Tajikistani',
            'Thai',
            'Tongan',
            'Tunisian',
            'Turkish',
            'Ukrainian',
            'Emirati',
            'British',
            'American',
            'Uruguayan',
            'Venezuelan',
            'Vietnamese',
            'Welsh',
            'Zambian',
            'Zimbabwean',
            'Burmese',
            'Montenegrin',
        ];

        foreach ($nationalities as $nationality) {
            DB::table('nationalities')->insert([
                'nationality' => $nationality
            ]);
        }
    }
}
