<?php

namespace Database\Seeders;

use App\Models\Address;
use App\Models\Fleet;
use App\Models\Rank;
use App\Models\University;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $crewData = [
            [
                'name' => 'CALSENA, RONITO JR H.',
                'personnel_id' => '219454',
                'age' => 49,
                'rank' => 'C/CK(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D2',
                'dob' => '1975-12-01',
                'permanent_address' => 'DUGMAN SAN DIONISIO (ILOILO) ILOILO',
                'tel' => '09606199351',
                'mobile' => '+639692109373',
                'email' => 'RHCALSENA1975.CREW@GMAIL.COM',
                'school' => 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE',
                'date_graduated' => '2005-03-30',
            ],
            [
                'name' => 'DUPIT, GIREMEL M.',
                'personnel_id' => '219456',
                'age' => 48,
                'rank' => 'OLR NO. 1(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E1',
                'dob' => '1976-12-09',
                'permanent_address' => 'MALOCLOC SUR IVISAN (CAPIZ) CAPIZ',
                'tel' => '9209598554',
                'mobile' => '+639618400453',
                'email' => 'DUPITGIREMEL@GMAIL.COM',
                'school' => 'COLEGIO DE LA PURISIMA CONCEPCION',
                'date_graduated' => '2003-05-30',
            ],
            [
                'name' => 'FLORENTINO, HAROLD C.',
                'personnel_id' => '219465',
                'age' => 43,
                'rank' => 'AB(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D2',
                'dob' => '1982-03-21',
                'permanent_address' => 'LOT 3, BLOCK 1, PHASE 1 SAN LORENZO HOMES SUBDIVISION, BARANGAY TANGUB BACOLOD (NEG. OCC.) NEGROS OCCIDENTAL',
                'tel' => '09369546532',
                'mobile' => '+639087955343',
                'email' => 'FLORENTINOHAROLD82@GMAIL.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION',
                'date_graduated' => '2002-03-21',
            ],
            [
                'name' => 'TONDO, HECTOR T.',
                'personnel_id' => '219471',
                'age' => 47,
                'rank' => 'AB(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D2',
                'dob' => '1978-06-25',
                'permanent_address' => 'B8 L3 NEDF VILLAGE HANDUMANAN BACOLOD (NEG. OCC.) NEGROS OCCIDENTAL',
                'tel' => '7048987',
                'mobile' => '+639271561695',
                'email' => 'HANZILOY01@GMAIL.COM',
                'school' => 'MTC COLLEGE - ILOILO',
                'date_graduated' => '1999-03-26',
            ],
            [
                'name' => 'GARCIA, LEONARD Q.',
                'personnel_id' => '219480',
                'age' => 46,
                'rank' => 'OLR NO. 1(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET A',
                'dob' => '1978-10-21',
                'permanent_address' => 'PUROK 7 RIZAL STREET  BRGY ALUA  SAN ISIDRO (NUEVA ECIJA) NUEVA ECIJA',
                'tel' => '',
                'mobile' => '+639393488556',
                'email' => 'DRANOELGARCIA21@GMAIL.COM',
                'school' => 'EULOGIO AMANG RODRIGUEZ INSTITUTE OF SCIENCE AND TECHNOLOGY',
                'date_graduated' => '1996-10-01',
            ],
            [
                'name' => 'PRIETO, HILARIO R.',
                'personnel_id' => '219482',
                'age' => 50,
                'rank' => 'OLR(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D2',
                'dob' => '1974-07-06',
                'permanent_address' => 'B-112 L-30 MABUHAY CITY MAMATID CABUYAO (LAGUNA) LAGUNA',
                'tel' => '',
                'mobile' => '+639054068786',
                'email' => 'LARRY.PRIETO06@GMAIL.COM',
                'school' => 'PHILIPPINE MARITIME INSTITUTE',
                'date_graduated' => '1998-03-31',
            ],
            [
                'name' => 'CILLACAY, RONIE A.',
                'personnel_id' => '219484',
                'age' => 42,
                'rank' => 'AB(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D1',
                'dob' => '1983-02-17',
                'permanent_address' => 'PUROK 2A GABUYAN KAPALONG (DAVAO DEL NORTE) DAVAO DEL NORTE',
                'tel' => '',
                'mobile' => '+639502032880',
                'email' => 'SCYINO1320@GMAIL.COM',
                'school' => 'DAVAO MERCHANT MARINE ACADEMY-DAVAO CITY',
                'date_graduated' => '2003-03-03',
            ],
            [
                'name' => 'MORENO, ROMEO JR V.',
                'personnel_id' => '219486',
                'age' => 43,
                'rank' => '1/AE-2(4)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D1',
                'dob' => '1981-11-27',
                'permanent_address' => 'NABAGATNAN, POBLACION JORDAN (GUIMARAS) GUIMARAS',
                'tel' => '09489001317',
                'mobile' => '+639482105583',
                'email' => 'ROMEO040318ILO@GMAIL.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION',
                'date_graduated' => '2004-10-05',
            ],
            [
                'name' => 'SOPSOP, STEPHEN .',
                'personnel_id' => '219491',
                'age' => 46,
                'rank' => 'OLR',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E1',
                'dob' => '1978-06-01',
                'permanent_address' => 'CM ENRIQUEZ STREET, SUBA DANAO CITY (CEBU) CEBU',
                'tel' => '',
                'mobile' => '+639668490505',
                'email' => 'STEPHENSOPSOP66@GMAIL.COM',
                'school' => 'CEBU STATE COLLEGE OF SCIENCE AND TECHNOLOGY',
                'date_graduated' => '2003-10-27',
            ],
            [
                'name' => 'PELAYO, FRANCIS S.',
                'personnel_id' => '219498',
                'age' => 46,
                'rank' => 'RABOUT',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'NTMA FLEET',
                'dob' => '1978-09-24',
                'permanent_address' => 'REFULGENTE STREET, BARANGAY ESTANCIA KALIBO (AKLAN) AKLAN',
                'tel' => '0949-350-4788',
                'mobile' => '+639493504788',
                'email' => 'PELAYO.FRANCIS@YAHOO.COM',
                'school' => 'AKLAN POLYTECHNIC INSTITUTE',
                'date_graduated' => '1998-03-23',
            ],
            [
                'name' => 'CALAMPINAY, RAFAEL JR J.',
                'personnel_id' => '219499',
                'age' => 40,
                'rank' => '2/AE(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1984-12-19',
                'permanent_address' => 'BLOCK 2 LOT 45 GREENTOWN VILL. 1 MAMBOG 2 BACOOR CAVITE',
                'tel' => '8717245',
                'mobile' => '+639491299775',
                'email' => 'RAFAELCALAMPINAY32@YAHOO.COM',
                'school' => 'WESTERN INSTITUTE OF TECHNOLOGY',
                'date_graduated' => '2005-10-17',
            ],
            [
                'name' => 'GARCERON, DANNE DAVIS F.',
                'personnel_id' => '219501',
                'age' => 41,
                'rank' => 'ELECT ENGR. 10',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C1',
                'dob' => '1984-02-22',
                'permanent_address' => 'LOT 19, BLOCK 1, IPIL STREET, MARIKINA HEIGHTS (CONCEPCION) MARIKINA CITY METRO MANILA',
                'tel' => '(02)945-9031',
                'mobile' => '+639197381302',
                'email' => 'DANNEDAVISGARCERON@GMAIL.COM',
                'school' => 'TECHNOLOGICAL UNIVERSITY OF THE PHILLIPPINES',
                'date_graduated' => '2006-03-28',
            ],
            [
                'name' => 'DELA TORRE, LEONIDES M.',
                'personnel_id' => '219503',
                'age' => 53,
                'rank' => 'C/CK(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET A',
                'dob' => '1971-09-22',
                'permanent_address' => 'PUROK 7 MOTO SUR LOON (BOHOL) BOHOL',
                'tel' => '09469437759',
                'mobile' => '+639995995159',
                'email' => 'LMDELATORRE1971.CREW@GMAIL.COM',
                'school' => 'PHILIPPINE MARINE INSTITUTE - BOHOL',
                'date_graduated' => '1995-10-15',
            ],
            [
                'name' => 'CONDINO, PEARL LOUEL CLYDE B.',
                'personnel_id' => '219505',
                'age' => 42,
                'rank' => 'FTR(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B2',
                'dob' => '1982-03-11',
                'permanent_address' => 'PHASE 3D  AREA 3 BLK 29 LOT 50 DAGAT-DAGATANA CALOOCAN CITY METRO MANILA',
                'tel' => '',
                'mobile' => '+639293329601',
                'email' => 'LOUELCLYDECONDINO@GMAIL.COM',
                'school' => 'PHILIPPINE MARITIME INSTITUTE-QUEZON CITY',
                'date_graduated' => '2004-10-03',
            ],
            [
                'name' => 'GRANADA, ROMMEL D.',
                'personnel_id' => '219515',
                'age' => 51,
                'rank' => 'OLR',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E2',
                'dob' => '1974-07-27',
                'permanent_address' => 'BLK. 7 LOT.31 CAMACHILE SUBD., PASONG GENERAL TRIAS CAVITE',
                'tel' => '',
                'mobile' => '+639064908138',
                'email' => 'ROMMELGRANADA1974@GMAIL.COM',
                'school' => 'PHILIPPINE MERCHANT MARINE ACADEMY',
                'date_graduated' => '1997-03-31',
            ],
            [
                'name' => 'CANALES, DENNIS PAOLO M.',
                'personnel_id' => '219518',
                'age' => 40,
                'rank' => '1/AE(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D1',
                'dob' => '1985-04-25',
                'permanent_address' => 'SHERIDAN TOWERS NORTH TOWER, SHERIDAN STREET, BARANGAY HIGHWAY HILLS MANDALUYONG CITY METRO MANILA',
                'tel' => '(02)87416058',
                'mobile' => '+639054641930',
                'email' => 'DPCANALES1985.CREW@GMAIL.COM',
                'school' => 'PHILIPPINE MERCHANT MARINE ACADEMY',
                'date_graduated' => '2009-05-23',
            ],
            [
                'name' => 'ABAYAO, EUGINE T.',
                'personnel_id' => '219546',
                'age' => 38,
                'rank' => 'C/M-2(4)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D1',
                'dob' => '1986-09-22',
                'permanent_address' => 'IBAYONG, BOCOS BANAUE (IFUGAO) IFUGAO',
                'tel' => '',
                'mobile' => '+639364596606',
                'email' => 'ABAYAOEUGINE@GMAIL.COM',
                'school' => 'PHILIPPINE MERCHANT MARINE ACADEMY',
                'date_graduated' => '2009-05-23',
            ],
            [
                'name' => 'ABCEDE, FRANK GIL G.',
                'personnel_id' => '219548',
                'age' => 44,
                'rank' => 'BSN(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1981-02-04',
                'permanent_address' => '02 MADERAL ST. LUCBAN (QUEZON) QUEZON',
                'tel' => '9194495766',
                'mobile' => '+639195470943',
                'email' => 'FRANCOALLYSON29@GMAIL.COM',
                'school' => 'INTER-GLOBAL MARITIME COLLEGE',
                'date_graduated' => '2002-04-05',
            ],
            [
                'name' => 'ABECIA, YSMAEL LUIS R.',
                'personnel_id' => '219551',
                'age' => 55,
                'rank' => 'C/CK',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'NTMA FLEET',
                'dob' => '1970-07-03',
                'permanent_address' => 'JP RIZAL ST., POBLACION DISTRICT I SAN VICENTE (CAM. NORTE) CAMARINES NORTE',
                'tel' => '09158104149',
                'mobile' => '+639091581041',
                'email' => 'YABECIA031970@GMAIL.COM',
                'school' => 'CAGAYAN DE ORO COLLEGES',
                'date_graduated' => '1989-03-13',
            ],
            [
                'name' => 'ABENION, RENATO B.',
                'personnel_id' => '219560',
                'age' => 53,
                'rank' => 'FTR(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C2',
                'dob' => '1972-03-18',
                'permanent_address' => 'PUROK SAN PEDRO, BARANGAY MARIA CLARA MAASIN CITY (S. LEYTE) SOUTHERN LEYTE',
                'tel' => '09157707966',
                'mobile' => '+639157707966',
                'email' => 'ABENIONRENATO85@GMAIL.COM',
                'school' => 'UNIVERSITY OF CEBU',
                'date_graduated' => '1992-03-30',
            ],
            [
                'name' => 'ABREA, ROEL F.',
                'personnel_id' => '219572',
                'age' => 56,
                'rank' => 'BSN(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E2',
                'dob' => '1969-06-26',
                'permanent_address' => 'BARANGAY CANDATAG MALITBOG (S. LEYTE) SOUTHERN LEYTE',
                'tel' => '',
                'mobile' => '+639773187670',
                'email' => 'ROELABREA1965@GMAIL.COM',
                'school' => 'PHILIPPINE MARITIME INSTITUTE',
                'date_graduated' => '1992-04-30',
            ],
            [
                'name' => 'ABRECE, DOMINGO B.',
                'personnel_id' => '219573',
                'age' => 53,
                'rank' => 'ENG ASST',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'NTMA FLEET',
                'dob' => '1971-11-14',
                'permanent_address' => 'PUROK BOUGAINVILLA BRGY. BANQUEROHAN CADIZ CITY (NEG. OCC.) NEGROS OCCIDENTAL',
                'tel' => '',
                'mobile' => '+639198025392',
                'email' => 'TIKBOYABRECE@YAHOO.COM',
                'school' => 'MTC COLLEGE',
                'date_graduated' => '1991-03-30',
            ],
            [
                'name' => 'ABRENICA, FRANNEL A.',
                'personnel_id' => '219575',
                'age' => 50,
                'rank' => 'MSTR(9)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1975-03-11',
                'permanent_address' => 'J. TAGLE ST., CUTA LOOBAN BATANGAS CITY (BATANGAS) BATANGAS',
                'tel' => '',
                'mobile' => '+639192962419',
                'email' => 'ABRENICAFRANNEL@YAHOO.COM',
                'school' => 'LYCEUM OF BATANGAS CITY',
                'date_graduated' => '1995-03-03',
            ],
            [
                'name' => 'ACACIO, JOSEPH JOHN A.',
                'personnel_id' => '219585',
                'age' => 48,
                'rank' => 'BSN(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1976-12-17',
                'permanent_address' => 'BLK 20, LOT 17, IBIZA HOMES, BRGY. GUINAYANG, SAN MATEO, RIZAL SAN MATEO (RIZAL) RIZAL',
                'tel' => '09560127362',
                'mobile' => '+639560127362',
                'email' => 'PAPAJOSH97@GMAIL.COM',
                'school' => 'PHILIPPINE MERCHANT MARINE SCHOOL',
                'date_graduated' => '1996-05-25',
            ],
            [
                'name' => 'ACALING, JULIUS G.',
                'personnel_id' => '219588',
                'age' => 43,
                'rank' => 'AB(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C1',
                'dob' => '1982-07-09',
                'permanent_address' => 'LOT 7 BLK 7 VILLA ESTIFANIA BACOLOD (NEG. OCC.) NEGROS OCCIDENTAL',
                'tel' => '09178018067',
                'mobile' => '+639668837769',
                'email' => 'JULIUSACALING@GMAIL.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION - BACOLOD',
                'date_graduated' => '2002-03-21',
            ],
            [
                'name' => 'ACAYLAR, ARVIN L.',
                'personnel_id' => '219590',
                'age' => 45,
                'rank' => 'MSTR(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B2',
                'dob' => '1979-11-17',
                'permanent_address' => '#28 RIZAL AVE. EXT CATBALOGAN (SAMAR) SAMAR',
                'tel' => '',
                'mobile' => '+639176861788',
                'email' => 'ACAYLARTRAVELNTOURS@GMAIL.COM',
                'school' => 'PHILIPPINE MARINE INSTITUTE - BOHOL',
                'date_graduated' => '1998-10-10',
            ],
            [
                'name' => 'ACEVEDO, GIOVANNI A.',
                'personnel_id' => '219592',
                'age' => 54,
                'rank' => 'C/M(4)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET A',
                'dob' => '1970-11-30',
                'permanent_address' => '2324, LEGASPI STREET, ILAYA, BARANGAY II ROXAS CITY CAPIZ',
                'tel' => '',
                'mobile' => '+639260644955',
                'email' => 'ACEVEDOGIOVANNIA@GMAIL.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION',
                'date_graduated' => '1994-08-27',
            ],
            [
                'name' => 'ACOSTA, ARNOL A.',
                'personnel_id' => '219596',
                'age' => 56,
                'rank' => 'OLR',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B2',
                'dob' => '1968-12-19',
                'permanent_address' => 'B-2 EMPLOYEES VILL UP DILIMAN QUEZON CITY METRO MANILA',
                'tel' => '',
                'mobile' => '+639566693101',
                'email' => '1968ARNOLACOSTA@GMAIL.COM',
                'school' => 'PHILIPPINE MERCHANT MARINE SCHOOL',
                'date_graduated' => '1991-03-05',
            ],
            [
                'name' => 'ACUPINPIN, LINGEL D.',
                'personnel_id' => '220603',
                'age' => 49,
                'rank' => 'MSTR(10)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1976-06-16',
                'permanent_address' => 'B32 L8 WESTWOOD SUBD. MANDURRIAO ILOILO CITY ILOILO',
                'tel' => '0333332300',
                'mobile' => '+639270842133',
                'email' => 'CMSTINGER76@GMAIL.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION',
                'date_graduated' => '1995-03-25',
            ],
            [
                'name' => 'ACUYONG, MARLON L.',
                'personnel_id' => '220604',
                'age' => 51,
                'rank' => 'BSN(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D2',
                'dob' => '1973-10-24',
                'permanent_address' => 'LOT4-I-10 FARMVILLE SUBD., PUROK-1, TIKAY MALOLOS (BULACAN) BULACAN',
                'tel' => '9471015413',
                'mobile' => '+639283111500',
                'email' => 'ACUYONGLHON@GMAIL.COM',
                'school' => 'PHILIPPINE MARITIME INSTITUTE',
                'date_graduated' => '1995-03-25',
            ],
            [
                'name' => 'ADEM, FRANCIS C.',
                'personnel_id' => '219615',
                'age' => 47,
                'rank' => 'AB(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D1',
                'dob' => '1977-08-15',
                'permanent_address' => 'POB. SEASIDE, VALENCIA (BOHOL) BOHOL',
                'tel' => '',
                'mobile' => '+639707749066',
                'email' => 'FRANZMARIE0308@GMAIL.COM',
                'school' => 'PHILIPPINE MARINE INSTITUTE - BOHOL',
                'date_graduated' => '1998-03-30',
            ],
            [
                'name' => 'AGNIR, DENNIS T.',
                'personnel_id' => '219648',
                'age' => 41,
                'rank' => 'ELECT ENGR. 10',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET A',
                'dob' => '1983-08-21',
                'permanent_address' => 'BRGY. 55-B SALET-BULANGON LAOAG CITY (ILOCOS NORTE) ILOCOS NORTE',
                'tel' => '09454708075',
                'mobile' => '+639669070045',
                'email' => 'AGNIRDENNIS@GMAIL.COM',
                'school' => 'MARIANO MARCOS STATE UNIVERSITY',
                'date_graduated' => '2006-04-04',
            ],
            [
                'name' => 'AGOS, VICENTE P.',
                'personnel_id' => '219650',
                'age' => 73,
                'rank' => 'MSTR',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1952-06-11',
                'permanent_address' => 'LOT1 BLOCK4 PHASE 5 CITA ITALIA SUBDIVISION, BUHAY NA TUBIG IMUS CAVITE',
                'tel' => '',
                'mobile' => '+639202435740',
                'email' => 'VICENTE_AGOS@YAHOO.COM',
                'school' => 'PHILIPPINE MARITIME INSTITUTE',
                'date_graduated' => '1974-10-03',
            ],
            [
                'name' => 'AGPALZA, EDGAR A.',
                'personnel_id' => '219651',
                'age' => 52,
                'rank' => 'FTR(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D2',
                'dob' => '1973-06-09',
                'permanent_address' => 'B16 L9 CHESTER PLACE BUROL MAIN DASMARIÑAS (CAVITE) CAVITE',
                'tel' => '',
                'mobile' => '+639977114497',
                'email' => 'AGPALZA1973@GMAIL.COM',
                'school' => 'TECHNOLOGICAL INSTITUTE OF THE PHIL.',
                'date_graduated' => '1994-03-30',
            ],
            [
                'name' => 'ALAGO, NARIO O.',
                'personnel_id' => '219691',
                'age' => 59,
                'rank' => 'BSN(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E1',
                'dob' => '1966-04-25',
                'permanent_address' => 'PUROK 3, TIGUIS LILA (BOHOL) BOHOL',
                'tel' => '',
                'mobile' => '+639451667092',
                'email' => 'NARIOALAGO@GMAIL.COM',
                'school' => 'PHILIPPINE MARITIME INSTITUTE',
                'date_graduated' => '1990-03-15',
            ],
            [
                'name' => 'ALAMEDA, MARK JOHN M.',
                'personnel_id' => '219694',
                'age' => 44,
                'rank' => 'AB(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C1',
                'dob' => '1981-01-31',
                'permanent_address' => 'BLK 3 LOT 2 VICTORS SUBD., COMMUNAL, BUHANGIN DAVAO CITY DAVAO DEL SUR',
                'tel' => '09493661213',
                'mobile' => '+639184230810',
                'email' => 'ALAMEDASUABE@GMAIL.COM',
                'school' => 'HOLY CROSS OF DAVAO COLLEGE',
                'date_graduated' => '2001-07-26',
            ],
            [
                'name' => 'ALDOVINO, JAMES A.',
                'personnel_id' => '219741',
                'age' => 44,
                'rank' => 'ELECT ENGR. 10',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1980-08-30',
                'permanent_address' => '"BRGY. STO. TOMAS\n\n TINGLOY (BATANGAS) BATANGAS"',
                'tel' => '',
                'mobile' => '+639178255513',
                'email' => 'JAMESALDOVINO24@GMAIL.COM',
                'school' => 'UNIVERSITY OF THE EAST',
                'date_graduated' => '2002-12-01',
            ],
            [
                'name' => 'ALEGORIA, JOSE JR D.',
                'personnel_id' => '219744',
                'age' => 53,
                'rank' => '2/AE(5)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E2',
                'dob' => '1972-02-05',
                'permanent_address' => 'B6, L20, PH1, TULIP STREET, GOLDEN HILLS SUBDIVISION, LOMA DE GATO MARILAO (BULACAN) BULACAN',
                'tel' => '',
                'mobile' => '+639668813024',
                'email' => 'ALEGORIAJRJOJO@GMAIL.COM',
                'school' => 'WESTERN INSTITUTE OF TECHNOLOGY - ILOILO',
                'date_graduated' => '1992-03-28',
            ],
            [
                'name' => 'ALEGRIA, JOEFFREY S.',
                'personnel_id' => '219745',
                'age' => 50,
                'rank' => 'BSN(1)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1974-09-15',
                'permanent_address' => 'BRGY TIRING CABATUAN (ILOILO) ILOILO',
                'tel' => '0905-4242196',
                'mobile' => '+639565903440',
                'email' => 'JOEFFREYALEGRIA@YAHOO.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION-ILOILO CITY',
                'date_graduated' => '1994-03-12',
            ],
            [
                'name' => 'ALEJANDRE, PHILLIP ARTHUR B.',
                'personnel_id' => '219748',
                'age' => 53,
                'rank' => 'AB',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B2',
                'dob' => '1972-07-04',
                'permanent_address' => '#840 ROSE STREET, POBLACION 2 BANSALAN (DAVAO DEL SUR) DAVAO DEL SUR',
                'tel' => '',
                'mobile' => '+639494988042',
                'email' => 'PHILIPALEJANDRE123@GMAIL.COM',
                'school' => 'DAVAO MERCHANT MARINE ACADEMY-DAVAO CITY',
                'date_graduated' => '1994-04-14',
            ],
            [
                'name' => 'ALEJANDRO, RICARDO JR A.',
                'personnel_id' => '219751',
                'age' => 54,
                'rank' => 'OLR(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D2',
                'dob' => '1970-08-18',
                'permanent_address' => 'CAROMANGAY, HAMTIC, ANTIQUE HAMTIC (ANTIQUE) ANTIQUE',
                'tel' => '8259570',
                'mobile' => '+639298210228',
                'email' => 'ALEJANDROSTEPHEN8@GMAIL.COM',
                'school' => 'WESTERN VISAYAS COLLEGE OF SCIENCE AND TECHNOLOGY',
                'date_graduated' => '1992-03-28',
            ],
            [
                'name' => 'ALEJO, EFREN JR M.',
                'personnel_id' => '219752',
                'age' => 49,
                'rank' => 'MSTR(5)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B2',
                'dob' => '1975-09-29',
                'permanent_address' => 'QUEZON ST, BRGY. MAT-Y MIAGAO (ILOILO) ILOILO',
                'tel' => '',
                'mobile' => '+639164985940',
                'email' => 'EFREN.ALEJO29@YAHOO.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION',
                'date_graduated' => '1995-03-05',
            ],
            [
                'name' => 'ALISDAN, DELFIN S.',
                'personnel_id' => '219768',
                'age' => 45,
                'rank' => 'C/E(10)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C2',
                'dob' => '1979-12-01',
                'permanent_address' => 'AD-205-F POBLACION LA TRINIDAD (BENGUET) BENGUET',
                'tel' => '',
                'mobile' => '+639286294142',
                'email' => 'KAMEMENG_KM63@YAHOO.COM',
                'school' => 'PHILIPPINE MERCHANT MARINE ACADEMY',
                'date_graduated' => '2003-06-28',
            ],
            [
                'name' => 'ALLA, ROMMEL T.',
                'personnel_id' => '219769',
                'age' => 44,
                'rank' => 'C/E(1)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C1',
                'dob' => '1980-10-18',
                'permanent_address' => 'BLK 1 LOT 8 KATHLEEN PLACE III SUBD., BRGY., PINAGKAISAHAN E. GARCIA ST., CUBAO,  QUEZON CITY METRO MANILA',
                'tel' => '9976591',
                'mobile' => '+639498315988',
                'email' => 'ROMMEL_ALLA@YAHOO.COM',
                'school' => 'PHILIPPINE MERCHANT MARINE ACADEMY',
                'date_graduated' => '2004-06-25',
            ],
            [
                'name' => 'ALLONAR, ROBINSON A.',
                'personnel_id' => '219774',
                'age' => 47,
                'rank' => 'OLR(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C2',
                'dob' => '1977-10-13',
                'permanent_address' => 'SITIO LINAO, BRGY BATO HINIGARAN (NEG. OCC.) NEGROS OCCIDENTAL',
                'tel' => '09198677809',
                'mobile' => '+639663749926',
                'email' => 'ALLONAR.1377@GMAIL.COM',
                'school' => 'ZAMBOANGA POLYTECHNIC COLLEGE',
                'date_graduated' => '1997-10-24',
            ],
            [
                'name' => 'ALMAZAN, DANILO R.',
                'personnel_id' => '219782',
                'age' => 52,
                'rank' => '2/M(4)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D1',
                'dob' => '1972-09-07',
                'permanent_address' => '18 YAKAL ST. CAREBI SUBD. ANGONO (RIZAL) RIZAL',
                'tel' => '',
                'mobile' => '+639059513248',
                'email' => 'DANNYALMAZAN2@GMAIL.COM',
                'school' => 'NAMEI POLYTECHNIC INSTITUTE',
                'date_graduated' => '1993-03-26',
            ],
            [
                'name' => 'ALMAZAN, JERRY P.',
                'personnel_id' => '219783',
                'age' => 59,
                'rank' => 'C/CK(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C1',
                'dob' => '1965-08-31',
                'permanent_address' => '110, SIXTO M. CACHO STREET, BARANGAY STA. MARIA CASTILLEJOS ZAMBALES',
                'tel' => '0928-389-4217',
                'mobile' => '+639283894217',
                'email' => 'JERRYALMAZAN65@GMAIL.COM',
                'school' => 'MARINER S POLYTECHNIC COLLEGES FOUNDATION',
                'date_graduated' => '1985-03-01',
            ],
            [
                'name' => 'ALUMIA, ALDEN S.',
                'personnel_id' => '219804',
                'age' => 44,
                'rank' => 'C/CK(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D2',
                'dob' => '1980-05-26',
                'permanent_address' => 'BRGY SOOC, AREVALO ILOILO CITY ILOILO',
                'tel' => '09454727229',
                'mobile' => '+639167591600',
                'email' => 'ALDEN_ALUMIA@YAHOO.COM',
                'school' => 'ILOILO STATE COLLEGE OF FISHERIES',
                'date_graduated' => '2000-03-27',
            ],
            [
                'name' => 'ALVAREZ, NATHANIEL T.',
                'personnel_id' => '219811',
                'age' => 51,
                'rank' => 'FTR(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E2',
                'dob' => '1973-12-01',
                'permanent_address' => 'DULCE 6 DONA SEGUNDINA TOWN HOMES NATIONAL HI-WAY PUTATAN MUNTINLUPA CITY METRO MANILA',
                'tel' => '744-3395',
                'mobile' => '+639617226197',
                'email' => 'NATHANIELALVAREZ176@GMAIL.COM',
                'school' => 'TECHNOLOGICAL INSTITUTE OF THE PHIL.',
                'date_graduated' => '1993-10-14',
            ],
            [
                'name' => 'AMATORIO, JOEBEN C.',
                'personnel_id' => '219822',
                'age' => 54,
                'rank' => '1/AE(4)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E2',
                'dob' => '1970-11-16',
                'permanent_address' => 'BLK. 18 L-2 BAMBOO ORCHARD, BANAYBANAY CABUYAO (LAGUNA) LAGUNA',
                'tel' => '',
                'mobile' => '+639568639084',
                'email' => 'JOEBENCAMATORIO@GMAIL.COM',
                'school' => 'UNIVERSITY OF ILOILO',
                'date_graduated' => '1989-10-15',
            ],
            [
                'name' => 'AMIHAN, RODEL L.',
                'personnel_id' => '219828',
                'age' => 47,
                'rank' => 'OLR NO. 1(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET A',
                'dob' => '1977-11-03',
                'permanent_address' => 'BRGY. PAGDUGUE DUMANGAS (ILOILO) ILOILO',
                'tel' => '09693052409',
                'mobile' => '+639693052409',
                'email' => 'LINGHON1977@GMAIL.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION',
                'date_graduated' => '2002-12-22',
            ],
            [
                'name' => 'AMISTOSO, JOEL D.',
                'personnel_id' => '219831',
                'age' => 54,
                'rank' => 'AB(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C1',
                'dob' => '1970-12-20',
                'permanent_address' => 'IMELDA LABASON (ZAMBOANGA DEL NORTE) ZAMBOANGA DEL NORTE',
                'tel' => '',
                'mobile' => '+639278576882',
                'email' => 'JOELAMISTOSO1970@GMAIL.COM',
                'school' => 'ZAMBOANGA STATE COLLEGE OF MARINE SCIENCE  AND TEC',
                'date_graduated' => '1991-03-27',
            ],
            [
                'name' => 'AMLOS, CLIFFTON O.',
                'personnel_id' => '219832',
                'age' => 51,
                'rank' => 'C/CK(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET A',
                'dob' => '1974-05-13',
                'permanent_address' => '#42, BARANGAY TACTAC SANTA FE (NUEVA VIZCAYA) NUEVA VIZCAYA',
                'tel' => '09553376212',
                'mobile' => '+639663485814',
                'email' => 'CLIFFTONAMLOS95@GMAIL.COM',
                'school' => 'SAINT MARY\'S COLLEGE',
                'date_graduated' => '1994-04-30',
            ],
            [
                'name' => 'AMONSOT, WILFREDO M.',
                'personnel_id' => '219836',
                'age' => 45,
                'rank' => 'C/M-2(3)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C2',
                'dob' => '1979-10-01',
                'permanent_address' => '15 LIGONES STREET, BOOL DISTRICT TAGBILARAN CITY (BOHOL) BOHOL',
                'tel' => '',
                'mobile' => '+639457299736',
                'email' => 'WILLAMONSOT@GMAIL.COM',
                'school' => 'PHILIPPINE MARINE INSTITUTE - BOHOL',
                'date_graduated' => '2000-10-01',
            ],
            [
                'name' => 'AMPIT, FELIX A.',
                'personnel_id' => '219843',
                'age' => 43,
                'rank' => 'BSN(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E1',
                'dob' => '1981-08-30',
                'permanent_address' => 'PUROK 3, LUMBAY PILAR (BOHOL) BOHOL',
                'tel' => '',
                'mobile' => '+639260772572',
                'email' => 'FELIXAMPIT@GMAIL.COM',
                'school' => 'PHILIPPINE MARINE INSTITUTE - BOHOL',
                'date_graduated' => '2001-03-30',
            ],
            [
                'name' => 'ANA, JIMMY A.',
                'personnel_id' => '219849',
                'age' => 48,
                'rank' => 'AB(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C1',
                'dob' => '1977-02-26',
                'permanent_address' => 'I-ABENIS ST BORONGAN (E. SAMAR) E. SAMAR',
                'tel' => '09676079550',
                'mobile' => '+639676079550',
                'email' => 'JIMMYANA28@GMAIL.COM',
                'school' => 'UNIVERSITY OF CEBU',
                'date_graduated' => '1998-10-19',
            ],
            [
                'name' => 'ANCHETA, DANILO GREGORY E.',
                'personnel_id' => '219852',
                'age' => 48,
                'rank' => 'BSN(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B2',
                'dob' => '1976-08-16',
                'permanent_address' => '161, BARANGAY SAN VICENTE SUR AGOO (LA UNION) LA UNION',
                'tel' => '',
                'mobile' => '+639282784621',
                'email' => 'DNNANCHETA@GMAIL.COM',
                'school' => 'NORTHERN PHILIPPINE COLLEGE FOR MARITIME STUDIES',
                'date_graduated' => '2003-10-30',
            ],
            [
                'name' => 'ANCHETA, MANUEL G.',
                'personnel_id' => '219855',
                'age' => 58,
                'rank' => 'FTR(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C2',
                'dob' => '1966-09-26',
                'permanent_address' => 'B3 LOT 8 VILLA MARIA SUBD. SAMBAT SAN PASCUAL (BATANGAS) BATANGAS',
                'tel' => '043-7271255',
                'mobile' => '+639297297299',
                'email' => 'MHANNYBOYANCHETA@GMAIL.COM',
                'school' => 'NPMTI -  LA UNION',
                'date_graduated' => '1984-11-08',
            ],
            [
                'name' => 'ANDIANO, RAYMUNDO S.',
                'personnel_id' => '219863',
                'age' => 53,
                'rank' => 'C/M(6)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B2',
                'dob' => '1971-10-14',
                'permanent_address' => 'BLOCK 18, LOT 6, PHASE 9, DECCA EXECUTIVE HOMES, BARANGAY TACUNAN DAVAO CITY DAVAO DEL SUR',
                'tel' => '',
                'mobile' => '+639761466824',
                'email' => 'RAYMUNDOANDIANO71@GMAIL.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION-ILOILO CITY',
                'date_graduated' => '1992-03-15',
            ],
            [
                'name' => 'ANDILLO, TOMAS D.',
                'personnel_id' => '221687',
                'age' => 59,
                'rank' => 'OLR NO. 1(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET A',
                'dob' => '1966-03-23',
                'permanent_address' => '#33 STA. CRUZ, CANDATING ARAYAT (PAMPANGA) PAMPANGA',
                'tel' => '',
                'mobile' => '+639192239799',
                'email' => 'DREUFERDINAND4@GMAIL.COM',
                'school' => 'GALLANOSA NATIONAL HIGHSCHOOL',
                'date_graduated' => '1984-03-03',
            ],
            [
                'name' => 'DUAY, JOAN B.',
                'personnel_id' => '221693',
                'age' => 48,
                'rank' => 'FTR(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C1',
                'dob' => '1976-11-12',
                'permanent_address' => '87 BANABA WEST  BATANGAS CITY (BATANGAS) BATANGAS',
                'tel' => '09617329622',
                'mobile' => '+639299744027',
                'email' => 'DUAYJOAN1112@GMAIL.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION',
                'date_graduated' => '1996-03-23',
            ],
            [
                'name' => 'DUENAS, MANUEL JR A.',
                'personnel_id' => '221699',
                'age' => 45,
                'rank' => 'AB(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D1',
                'dob' => '1979-05-27',
                'permanent_address' => 'BLOCK 7, LOT 1, JEM SUBDIVISION, BARANGAY GUZMAN-JESENA ILOILO CITY ILOILO',
                'tel' => '09284819615',
                'mobile' => '+639483580986',
                'email' => 'MADUENAS1979.CREW@GMAIL.COM',
                'school' => 'JOHN B. LACSON COLLEGE FOUNDATION-ILOILO CITY',
                'date_graduated' => '2002-10-30',
            ],
            [
                'name' => 'DULALAS, FLORENCIO M.',
                'personnel_id' => '221707',
                'age' => 44,
                'rank' => 'C/M(1)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1981-02-03',
                'permanent_address' => 'PUROK 2, CATARMAN DAUIS (BOHOL) BOHOL',
                'tel' => '',
                'mobile' => '+639763050476',
                'email' => 'FDULALAS1981.CREW@GMAIL.COM',
                'school' => 'PHILIPPINE MARINE INSTITUTE - BOHOL',
                'date_graduated' => '2001-03-03',
            ],
            [
                'name' => 'DUMA, MAYDAN A.',
                'personnel_id' => '221720',
                'age' => 48,
                'rank' => 'C/E(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET A',
                'dob' => '1977-05-16',
                'permanent_address' => '335 TAMBLOT STREET TAGBILARAN CITY (BOHOL) BOHOL',
                'tel' => '09178940281',
                'mobile' => '+639664652147',
                'email' => 'MAYDANDUMA1977@GMAIL.COM',
                'school' => 'PHILIPPINE MERCHANT MARINE SCHOOL LAS PIÑAS CITY',
                'date_graduated' => '1997-03-30',
            ],
            [
                'name' => 'DUMAGAT, GEMELO JR P.',
                'personnel_id' => '221721',
                'age' => 49,
                'rank' => 'BSN(2)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B1',
                'dob' => '1975-11-26',
                'permanent_address' => '971B GOLDEN RIBBON, BUTUAN CITY AGUSAN DEL NORTE',
                'tel' => '',
                'mobile' => '+639668773988',
                'email' => 'DUMAGAT_G@YAHOO.COM',
                'school' => 'SAINT JOSEPH INSTITUTE OF TECHNOLOGY',
                'date_graduated' => '1995-03-03',
            ],
            [
                'name' => 'DUNGO, ANGELITO JR A.',
                'personnel_id' => '221731',
                'age' => 43,
                'rank' => 'ELECT ENGR. 10',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET B2',
                'dob' => '1982-06-18',
                'permanent_address' => '#810 BRGY. STO. DOMINGO MINALIN (PAMPANGA) PAMPANGA',
                'tel' => '',
                'mobile' => '+639167401962',
                'email' => 'BANGAY18@GMAIL.COM',
                'school' => 'BULACAN STATE UNIVERSITY',
                'date_graduated' => '2006-04-01',
            ],
            [
                'name' => 'DURA, VALENTIN O.',
                'personnel_id' => '221734',
                'age' => 58,
                'rank' => 'BSN(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C1',
                'dob' => '1966-10-25',
                'permanent_address' => '215 CALANGAY SAN NICOLAS (BATANGAS) BATANGAS',
                'tel' => '09289994840',
                'mobile' => '+639474005122',
                'email' => 'DURAVALENTIN25@GMAIL.COM',
                'school' => 'PHILIPPINE MERCHANT MARINE SCHOOL',
                'date_graduated' => '1990-10-20',
            ],
            [
                'name' => 'EBORDA, ARMANDO B.',
                'personnel_id' => '221748',
                'age' => 60,
                'rank' => 'P/MAN(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C2',
                'dob' => '1964-12-05',
                'permanent_address' => 'BLK 7 LOT 6 TIERRA GRANDE 3-D CAMELLA HOMES LAWA-AN TALISAY CITY (CEBU) CEBU',
                'tel' => '0927-778-9295',
                'mobile' => '+639567867949',
                'email' => 'ABEBORDA@GMAIL.COM',
                'school' => 'CEBU CENTRAL COLLEGES',
                'date_graduated' => '1989-01-03',
            ],
            [
                'name' => 'ECHON, RIZAL E.',
                'personnel_id' => '221759',
                'age' => 46,
                'rank' => 'AB(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D2',
                'dob' => '1978-12-30',
                'permanent_address' => 'E-159 DIRITA-BALOGUEN IBA (ZAMBALES) ZAMBALES',
                'tel' => '09389272763',
                'mobile' => '+639982582725',
                'email' => 'RIZALECHON78@GMAIL.COM',
                'school' => 'VIRGEN DELOS REMEDIOS COLLEGE',
                'date_graduated' => '1999-03-30',
            ],
            [
                'name' => 'EDONG, ARTURO B.',
                'personnel_id' => '221768',
                'age' => 57,
                'rank' => 'C/E(4)',
                'crew_status' => 'ON VACATION',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E2',
                'dob' => '1967-10-21',
                'permanent_address' => 'BLK-7 LOT 50 CHINA ST. BARCELONA 4 BUHAY NA TUBIG IMUS CAVITE',
                'tel' => '',
                'mobile' => '+639286627266',
                'email' => 'ART_EDONG@YAHOO.COM',
                'school' => 'TECHNOLOGICAL INSTITUTE OF THE PHIL.',
                'date_graduated' => '1987-03-01',
            ],
            [
                'name' => 'EDRADA, LUCIANO C.',
                'personnel_id' => '221769',
                'age' => 66,
                'rank' => '2/E(4)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET E2',
                'dob' => '1959-06-13',
                'permanent_address' => 'SOUTH SAN JOSE ST., MOLO ILOILO CITY ILOILO',
                'tel' => '351-22-68',
                'mobile' => '+639491747699',
                'email' => 'EDRADALUCIANO@GMAIL.COM',
                'school' => 'ILOILO MARITIME ACADEMY',
                'date_graduated' => '1982-03-01',
            ],
            [
                'name' => 'ENERLAN, ENGIEMAR S.',
                'personnel_id' => '221808',
                'age' => 43,
                'rank' => 'AB(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET D1',
                'dob' => '1981-07-30',
                'permanent_address' => 'ADELFA, ACMAC ILIGAN CITY LANAO DEL NORTE',
                'tel' => '',
                'mobile' => '+639952979395',
                'email' => 'GGEM_ENERLAN@YAHOO.COM',
                'school' => 'LYCEUM OF ILIGAN',
                'date_graduated' => '2001-03-26',
            ],
            [
                'name' => 'ENGO, FELIMON A.',
                'personnel_id' => '221810',
                'age' => 56,
                'rank' => 'RABOUT-PHR',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'NTMA FLEET',
                'dob' => '1969-03-22',
                'permanent_address' => 'POTONG, LAPINIG (N. SAMAR) NORTHERN SAMAR',
                'tel' => '9567508541',
                'mobile' => '9567508498',
                'email' => '',
                'school' => 'PHILIPPINE MARITIME INSTITUTE',
                'date_graduated' => '1993-03-01',
            ],
            [
                'name' => 'ESCABILLAS, JOSE MARIE L.',
                'personnel_id' => '221833',
                'age' => 54,
                'rank' => 'OLR(2)',
                'crew_status' => 'ON BOARD',
                'hire_status' => 'RE-HIRE',
                'fleet' => 'FLEET C2',
                'dob' => '1971-04-15',
                'permanent_address' => '11-A JEREOS EXTENSION, LAPAZ, LOPEZ JAENA SUR ILOILO CITY ILOILO',
                'tel' => '09062225613',
                'mobile' => '+639062225615',
                'email' => 'JOSEMARIEESCABILLAS15@GMAIL.COM',
                'school' => 'WESTERN VISAYAS COLLEGE OF SCIENCE AND TECHNOLOGY',
                'date_graduated' => '1996-03-22',
            ],
        ];

        foreach ($crewData as $data) {
            // Parse the name
            $nameParts = $this->parseName($data['name']);

            // Find fleet
            $fleet = Fleet::where('name', $data['fleet'])->first();

            // Find rank
            $rank = Rank::where('name', $data['rank'])->first();

            // Find university
            $university = University::where('name', $data['school'])->first();

            // Find address
            $address = Address::where('street_address', 'LIKE', '%' . $data['permanent_address'] . '%')->first();

            // Create user
            User::firstOrCreate([
                'crew_id' => $data['personnel_id'],
            ], [
                'is_crew' => true,
                'email' => strtolower($data['email']),
                'password' => Hash::make('password'), // Default password
                // 'first_name' => $nameParts['first_name'],
                // 'middle_name' => $nameParts['middle_name'],
                // 'last_name' => $nameParts['last_name'],
                // 'suffix' => $nameParts['suffix'],
                // 'date_of_birth' => Carbon::parse($data['dob']),
                // 'gender' => 'Male', // Assuming male from the data
                // 'mobile_number' => $data['mobile'],
                // 'crew_status' => strtolower(str_replace(' ', '_', $data['crew_status'])),
                // 'hire_status' => strtolower(str_replace('-', '_', $data['hire_status'])),
                // 'fleet_id' => $fleet?->id,
                // 'rank_id' => $rank?->id,
                // 'graduated_school_id' => $university?->id,
                // 'date_graduated' => $data['date_graduated'] ? Carbon::parse($data['date_graduated']) : null,
                // 'permanent_address_id' => $address?->id,
            ]);
        }
    }

    /**
     * Parse a full name into components
     */
    private function parseName(string $fullName): array
    {
        // Remove extra spaces and clean the name
        $fullName = trim(preg_replace('/\s+/', ' ', $fullName));

        // Handle suffix first
        $suffix = null;
        if (preg_match('/\b(JR\.?|SR\.?|III|IV|V)\b/i', $fullName, $matches)) {
            $suffix = strtoupper(trim($matches[0], '.'));
            $fullName = trim(str_replace($matches[0], '', $fullName));
        }

        // Split by comma first (last name, first name format)
        if (strpos($fullName, ',') !== false) {
            $parts = explode(',', $fullName, 2);
            $lastName = trim($parts[0]);
            $firstMiddle = trim($parts[1]);

            // Split first and middle names
            $firstMiddleParts = explode(' ', $firstMiddle);
            $firstName = array_shift($firstMiddleParts);
            $middleName = implode(' ', $firstMiddleParts);
        } else {
            // Split by spaces
            $parts = explode(' ', $fullName);
            $firstName = array_shift($parts);
            $lastName = array_pop($parts);
            $middleName = implode(' ', $parts);
        }

        return [
            'first_name' => $firstName ?: null,
            'middle_name' => $middleName ?: null,
            'last_name' => $lastName ?: null,
            'suffix' => $suffix,
        ];
    }
}
