<?php

namespace Database\Seeders;

use App\Models\Vessel;
use Illuminate\Database\Seeder;

class VesselSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vesselsData = [
            // Fleet A (fleet_id = 1)
            ['name' => 'SG Ocean', 'fleet_id' => 1, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'SG Twilight', 'fleet_id' => 1, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'SG Aquamarine', 'fleet_id' => 1, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'SG Sunrise', 'fleet_id' => 1, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'SG Dawn', 'fleet_id' => 1, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'SG Lagoon', 'fleet_id' => 1, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'NBA Monet', 'fleet_id' => 1, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'NBA Vermeer', 'fleet_id' => 1, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'NBA Magritte', 'fleet_id' => 1, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'NBA Van Dyck', 'fleet_id' => 1, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'NBA Millet', 'fleet_id' => 1, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'Atlantic Elm', 'fleet_id' => 1, 'vessel_type_id' => 5, 'prefix' => 'MV'],
            ['name' => 'Paraburdoo', 'fleet_id' => 1, 'vessel_type_id' => 6, 'prefix' => 'MV'],
            ['name' => 'Procyon Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Sakura Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Plumeria Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Jasmine Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Castor Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Delphinus Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Dionysos Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Daedalus Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Selene Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Libra Leader', 'fleet_id' => 1, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Shoyo', 'fleet_id' => 1, 'vessel_type_id' => 8, 'prefix' => 'MV'],
            ['name' => 'Sol Explorer', 'fleet_id' => 1, 'vessel_type_id' => 8, 'prefix' => 'SG'],
            ['name' => 'Sakura Crescent', 'fleet_id' => 1, 'vessel_type_id' => 8, 'prefix' => 'MV'],

            // Fleet B1 (fleet_id = 2)
            ['name' => 'Atlas Leader', 'fleet_id' => 2, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Andromeda Leader', 'fleet_id' => 2, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Dione  Leader', 'fleet_id' => 2, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Crux Leader', 'fleet_id' => 2, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Vela Leader', 'fleet_id' => 2, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Pyxis Leader', 'fleet_id' => 2, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Helios Leader', 'fleet_id' => 2, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Pavo Leader', 'fleet_id' => 2, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Dawn Horizon', 'fleet_id' => 2, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Frontier Discovery', 'fleet_id' => 2, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Frontier Rose', 'fleet_id' => 2, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Frontier Sky', 'fleet_id' => 2, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Frontier Harvest', 'fleet_id' => 2, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Frontier Wave', 'fleet_id' => 2, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Saiko', 'fleet_id' => 2, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Taharoa Destiny', 'fleet_id' => 2, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Saga Fuji', 'fleet_id' => 2, 'vessel_type_id' => 5, 'prefix' => 'MV'],
            ['name' => 'Saga Viking', 'fleet_id' => 2, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'FP Future', 'fleet_id' => 2, 'vessel_type_id' => 9, 'prefix' => 'MV'],
            ['name' => 'Forestal Reina', 'fleet_id' => 2, 'vessel_type_id' => 9, 'prefix' => 'MV'],
            ['name' => 'White Princess', 'fleet_id' => 2, 'vessel_type_id' => 9, 'prefix' => 'MV'],

            // Fleet B2 (fleet_id = 3)
            ['name' => 'Ore Noumea', 'fleet_id' => 3, 'vessel_type_id' => 11, 'prefix' => null],
            ['name' => 'Wugang Innovation', 'fleet_id' => 3, 'vessel_type_id' => 11, 'prefix' => 'MV'],
            ['name' => 'Moonlight Dolphin', 'fleet_id' => 3, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Frontier Jacaranda', 'fleet_id' => 3, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Golden Horizon', 'fleet_id' => 3, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Shin Suma', 'fleet_id' => 3, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Emerald Horizon', 'fleet_id' => 3, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Key Hunter', 'fleet_id' => 3, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'Rising Sun', 'fleet_id' => 3, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'Maizuru Bishamon', 'fleet_id' => 3, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'Elegant Salute', 'fleet_id' => 3, 'vessel_type_id' => 4, 'prefix' => 'MV'],
            ['name' => 'Asahi Maru', 'fleet_id' => 3, 'vessel_type_id' => 8, 'prefix' => 'MV'],
            ['name' => 'Sunrise Serenity', 'fleet_id' => 3, 'vessel_type_id' => 8, 'prefix' => 'MV'],
            ['name' => 'JP Caretta', 'fleet_id' => 3, 'vessel_type_id' => 8, 'prefix' => 'MV'],
            ['name' => 'Key Action', 'fleet_id' => 3, 'vessel_type_id' => 8, 'prefix' => 'MV'],
            ['name' => 'Cetus Leader', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Poseidon Leader', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Aries Leader', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Artemis Leader', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Phoenix Leader', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Iris Leader', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'King Quest', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Freesia Leader', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Sumire Leader', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Pleiades Leader', 'fleet_id' => 3, 'vessel_type_id' => 7, 'prefix' => 'MV'],

            // Fleet C1 (fleet_id = 4)
            ['name' => 'Pacific Notus', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'LNG Ogun', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Grace Acacia', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'LNG Borno', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Energy Confidence', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'LNG Barka', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Energy Horizon', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Pacific Arcadia', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Sakura', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'LNG'],
            ['name' => 'Marvel Falcon', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Ejnan', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'LNG Dream', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Energy Glory', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Marvel Crane', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Diamond Gas Orchid', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Diamond Gas Sakura', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Elisa Larus', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'LNG Adventure', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'LNG Enterprise', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'LNG Endeavour', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'LNG Endurance', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Elisa Aquila', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Elisa Ardea', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Broog', 'fleet_id' => 4, 'vessel_type_id' => 12, 'prefix' => 'SS'],

            // Fleet C2 (fleet_id = 5)
            ['name' => 'Tenki', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Tamba', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Tango', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Tsugaru', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Takamatsu Maru', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Takaoka', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Towada', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Tanzawa', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Toya', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Pertamina Pride', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => null],
            ['name' => 'Pertamina Prime', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => null],
            ['name' => 'Tateshina', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Towa Maru', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Taga', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Tenryu', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Ikigai', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MV'],
            ['name' => 'Tensho', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Tosa', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Tenjun', 'fleet_id' => 5, 'vessel_type_id' => 13, 'prefix' => 'MT'],
            ['name' => 'Challenge Prime', 'fleet_id' => 5, 'vessel_type_id' => 14, 'prefix' => 'MT'],
            ['name' => 'World Navigator', 'fleet_id' => 5, 'vessel_type_id' => 14, 'prefix' => 'MT'],
            ['name' => 'Takaroa Sun', 'fleet_id' => 5, 'vessel_type_id' => 14, 'prefix' => 'MT'],
            ['name' => 'Seymour Sun', 'fleet_id' => 5, 'vessel_type_id' => 14, 'prefix' => 'MT'],
            ['name' => 'Grouse Sun', 'fleet_id' => 5, 'vessel_type_id' => 14, 'prefix' => 'MT'],

            // Fleet D1 (fleet_id = 6)
            ['name' => 'Cygnus Passage', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Grace Barleria', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Al Thumama', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'MV'],
            ['name' => 'Al Utouriya', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'MV'],
            ['name' => 'Lusail', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Al Jasra', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Al Khor', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'AL Sahla', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'MV'],
            ['name' => 'Grand Elena', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Doha', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Taitar No. 1', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Taitar No. 2', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Taitar No. 3', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Seishu Maru', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Green Zeebrugee', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Diamond Gas Rose', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Shinshu Maru', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Diamond Gas Metropolis', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Grand Aniva', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Grace Dahlia', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Al Zuwair', 'fleet_id' => 6, 'vessel_type_id' => 12, 'prefix' => null],

            // Fleet D2 (fleet_id = 7)
            ['name' => 'Malanje', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Cubal', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Bushu Maru', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Pacific Enlighten', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'LNG Jupiter', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Diamond Gas Crystal', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Diamond Gas Victoria', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Grace Emilia', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Grace Freesia', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Pacific Mimosa', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Quest Kirishima', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => null],
            ['name' => 'Taitar No. 4', 'fleet_id' => 7, 'vessel_type_id' => 12, 'prefix' => 'SS'],
            ['name' => 'Legend Prestige', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Legend Prosperity', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Leto Providence', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Gas Capricorn', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Laurel Prime', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Lilac Promenade', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Lupinus Planet', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Lantana Planet', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Gas Amethyst', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Liberty Pathfinder', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Lucina Providence', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Gas Garnet', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],
            ['name' => 'Luna Pathfinder', 'fleet_id' => 7, 'vessel_type_id' => 15, 'prefix' => 'MT'],

            // Fleet E1 (fleet_id = 8)
            ['name' => 'NYK Vega', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'ONE Theseus', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Diana', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'ONE Wren', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Romulus', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'ONE Altair', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'One Owl', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Clara', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'ACX Diamond', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Daedalus', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Laura', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Remus', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Rigel', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Joanna', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'One Stork', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'One Aquilla', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'One Columba', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'One Grus', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'One Apus', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'One Cygnus', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Oceanus', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'NYK Furano', 'fleet_id' => 8, 'vessel_type_id' => 16, 'prefix' => 'MV'],
            ['name' => 'Lyra Leader', 'fleet_id' => 8, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Hestia Leader', 'fleet_id' => 8, 'vessel_type_id' => 7, 'prefix' => 'MV'],
            ['name' => 'Daisy Leader', 'fleet_id' => 8, 'vessel_type_id' => 7, 'prefix' => 'MV'],

            // Fleet E2 (fleet_id = 9)
            ['name' => 'BNS Dongshan', 'fleet_id' => 9, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Taharoa Providence', 'fleet_id' => 9, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Buena Ventura', 'fleet_id' => 9, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Fuji Horizon', 'fleet_id' => 9, 'vessel_type_id' => 3, 'prefix' => 'MV'],
            ['name' => 'Rhea Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Venus Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Virgo Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Dorado Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Sarah Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Orion Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Altair Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Zeus Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Hercules Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Aquarius Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Auriga Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Deneb Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Cassiopeia Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Monoceros Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
            ['name' => 'Mercury Leader', 'fleet_id' => 9, 'vessel_type_id' => 17, 'prefix' => 'MV'],
        ];

        $x = 1;
        foreach ($vesselsData as $data) {
            Vessel::firstOrCreate(
                ['name' => $data['name']],
                [
                    'vessel_id' => $x,
                    'fleet_id' => $data['fleet_id'],
                    'vessel_type_id' => $data['vessel_type_id'],
                    'prefix' => $data['prefix'],
                ]
            );
            $x++;
        }
    }
}
